import type { ActionDefinition } from '../../shared/actions'

export const ACTION_REGISTRY: ActionDefinition[] = [
  {
    id: 'clipboard-write',
    name: 'Copy to clipboard',
    tier: 'safe',
    category: 'clipboard',
    description: 'Write text to the system clipboard',
    params: [{ name: 'text', type: 'string', required: true, description: 'Text to copy' }],
  },
  {
    id: 'open-url',
    name: 'Open URL',
    tier: 'safe',
    category: 'navigation',
    description: 'Open a URL in the default browser',
    params: [{ name: 'url', type: 'string', required: true, description: 'HTTP or HTTPS URL' }],
  },
  {
    id: 'open-file',
    name: 'Open file',
    tier: 'safe',
    category: 'os',
    description: 'Open a file with its default application',
    params: [{ name: 'path', type: 'string', required: true, description: 'Absolute file path' }],
  },
  {
    id: 'reveal-in-folder',
    name: 'Reveal in file manager',
    tier: 'safe',
    category: 'os',
    description: 'Show a file or folder in Windows Explorer',
    params: [{ name: 'path', type: 'string', required: true, description: 'Absolute file path' }],
  },
  {
    id: 'save-note',
    name: 'Save note',
    tier: 'safe',
    category: 'notes',
    description: 'Save a text note linked to the current window/app',
    params: [
      { name: 'text', type: 'string', required: true, description: 'Note content' },
      { name: 'title', type: 'string', required: false, description: 'Note title (auto-generated if omitted)' },
    ],
  },
  {
    id: 'list-notes',
    name: 'List notes',
    tier: 'safe',
    category: 'notes',
    description: 'List all saved notes',
    params: [],
  },
  {
    id: 'get-note',
    name: 'Read note',
    tier: 'safe',
    category: 'notes',
    description: 'Read a saved note by ID',
    params: [{ name: 'id', type: 'string', required: true, description: 'Note ID' }],
  },
  {
    id: 'delete-note',
    name: 'Delete note',
    tier: 'safe',
    category: 'notes',
    description: 'Delete a saved note by ID',
    params: [{ name: 'id', type: 'string', required: true, description: 'Note ID' }],
  },
  {
    id: 'set-reminder',
    name: 'Set reminder',
    tier: 'safe',
    category: 'notifications',
    description: 'Schedule a one-time OmniCue reminder notification',
    params: [
      { name: 'message', type: 'string', required: true, description: 'Reminder message' },
      { name: 'delaySeconds', type: 'number', required: true, description: 'Seconds until the reminder fires' },
    ],
  },
  {
    id: 'search-web',
    name: 'Search the web',
    tier: 'safe',
    category: 'navigation',
    description: 'Open a web search for the provided query',
    params: [{ name: 'query', type: 'string', required: true, description: 'Search query' }],
  },
  {
    id: 'find-file',
    name: 'Find file',
    tier: 'safe',
    category: 'os',
    description: 'Search for matching files and return their paths',
    params: [
      { name: 'pattern', type: 'string', required: true, description: 'File name or wildcard pattern' },
      { name: 'startDir', type: 'string', required: false, description: 'Directory to search from' },
    ],
  },
  {
    id: 'list-running-apps',
    name: 'List running apps',
    tier: 'safe',
    category: 'os',
    description: 'List visible running applications',
    params: [],
  },
  // ── Browser enrichment actions (safe) ──────────────────────────────────────
  {
    id: 'browser-url',
    name: 'Get browser URL',
    tier: 'safe',
    category: 'browser',
    description: 'Extract the current browser URL from the address bar',
    params: [],
  },
  {
    id: 'browser-page-content',
    name: 'Get page content',
    tier: 'safe',
    category: 'browser',
    description: 'Fetch and parse structured page content (title, headings, links, article)',
    params: [{ name: 'url', type: 'string', required: false, description: 'URL to fetch (uses browser URL if omitted)' }],
  },
  {
    id: 'browser-readable',
    name: 'Get readable article',
    tier: 'safe',
    category: 'browser',
    description: 'Get a clean readable version of the current page',
    params: [{ name: 'url', type: 'string', required: false, description: 'URL to fetch (uses browser URL if omitted)' }],
  },
  {
    id: 'browser-headings',
    name: 'Get page headings',
    tier: 'safe',
    category: 'browser',
    description: 'Extract the heading structure of a page',
    params: [{ name: 'url', type: 'string', required: false, description: 'URL to fetch (uses browser URL if omitted)' }],
  },
  {
    id: 'browser-links',
    name: 'Get page links',
    tier: 'safe',
    category: 'browser',
    description: 'Extract all links from a page',
    params: [{ name: 'url', type: 'string', required: false, description: 'URL to fetch (uses browser URL if omitted)' }],
  },
  {
    id: 'browser-fonts',
    name: 'Identify page fonts',
    tier: 'safe',
    category: 'browser',
    description: 'Identify all fonts used on a webpage',
    params: [{ name: 'url', type: 'string', required: false, description: 'URL to inspect (uses browser URL if omitted)' }],
  },
  {
    id: 'browser-selected-text',
    name: 'Read selected text',
    tier: 'safe',
    category: 'browser',
    description: 'Read the currently selected text in the browser via UI Automation',
    params: [],
  },
  // ── Browser control actions (guided) ─────────────────────────────────────
  {
    id: 'browser-back',
    name: 'Navigate back',
    tier: 'guided',
    category: 'browser',
    description: 'Navigate back in the focused browser',
    params: [],
  },
  {
    id: 'browser-forward',
    name: 'Navigate forward',
    tier: 'guided',
    category: 'browser',
    description: 'Navigate forward in the focused browser',
    params: [],
  },
  {
    id: 'browser-refresh',
    name: 'Refresh page',
    tier: 'guided',
    category: 'browser',
    description: 'Refresh the focused browser tab',
    params: [],
  },
  {
    id: 'browser-focus-address-bar',
    name: 'Focus address bar',
    tier: 'guided',
    category: 'browser',
    description: 'Focus the browser address bar',
    params: [],
  },
  {
    id: 'browser-copy-url',
    name: 'Copy URL',
    tier: 'guided',
    category: 'browser',
    description: 'Copy the current URL via address-bar key flow',
    params: [],
  },
  {
    id: 'browser-selected-text-capture',
    name: 'Capture selected text',
    tier: 'guided',
    category: 'browser',
    description: 'Capture selected text via clipboard dance (sends Ctrl+C)',
    params: [],
  },
  {
    id: 'browser-font-download',
    name: 'Download font',
    tier: 'guided',
    category: 'browser',
    description: 'Download and convert a font from a webpage to disk',
    params: [
      { name: 'fontUrl', type: 'string', required: true, description: 'URL of the font file' },
      { name: 'family', type: 'string', required: false, description: 'Font family name for the filename' },
      { name: 'destDir', type: 'string', required: true, description: 'Directory to save the font' },
    ],
  },
  // ── Input actions ────────────────────────────────────────────────────────
  {
    id: 'type-text',
    name: 'Type text',
    tier: 'guided',
    category: 'input',
    description: 'Type text into the currently focused field',
    params: [{ name: 'text', type: 'string', required: true, description: 'Text to type' }],
  },
  {
    id: 'press-key',
    name: 'Press key',
    tier: 'guided',
    category: 'input',
    description: 'Press a keyboard shortcut (e.g. "ctrl+s", "alt+tab", "enter")',
    params: [{ name: 'keys', type: 'string', required: true, description: 'Key combo like "ctrl+s" or "alt+f4"' }],
  },
  {
    id: 'click-element',
    name: 'Click UI element',
    tier: 'guided',
    category: 'input',
    description: 'Click a UI element by automation name or screen coordinates',
    params: [
      { name: 'name', type: 'string', required: false, description: 'UI Automation name of the element' },
      { name: 'x', type: 'number', required: false, description: 'Screen X coordinate' },
      { name: 'y', type: 'number', required: false, description: 'Screen Y coordinate' },
    ],
  },
  {
    id: 'switch-app',
    name: 'Switch to app',
    tier: 'guided',
    category: 'navigation',
    description: 'Bring an application window to the foreground',
    params: [{ name: 'processName', type: 'string', required: true, description: 'Process name or window title substring' }],
  },
  {
    id: 'delete-file',
    name: 'Delete file',
    tier: 'dangerous',
    category: 'os',
    description: 'Move a file to the recycle bin',
    params: [{ name: 'path', type: 'string', required: true, description: 'Absolute file path to delete' }],
  },
  {
    id: 'send-input',
    name: 'Send message',
    tier: 'dangerous',
    category: 'input',
    description: 'Press Enter to send a composed message in the active app',
    params: [{ name: 'confirm', type: 'boolean', required: true, description: 'Must be true to proceed' }],
  },
  {
    id: 'submit-form',
    name: 'Submit form',
    tier: 'dangerous',
    category: 'input',
    description: 'Click Submit or press Enter on a form',
    params: [{ name: 'confirm', type: 'boolean', required: true, description: 'Must be true to proceed' }],
  },
]
